name: "참여 조직 추가"
description: "용어집 프로젝트에 참여하는 조직을 추가합니다"
title: "[ORG] "
labels: ["organization-addition", "partnership"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🏢 참여 조직 추가
        
        AI/ML 용어집 프로젝트에 참여하는 조직을 추가하는 템플릿입니다.
        참여 조직은 프로젝트 후원, 전문성 제공, 홍보 등의 형태로 기여할 수 있습니다.
        
        **중요**: 모든 필수 필드(*)를 작성해 주세요.

  - type: dropdown
    id: organization_type
    attributes:
      label: 조직 유형 *
      description: "조직의 유형을 선택하세요"
      options:
        - "대학 (University)"
        - "기업 (Company)"
        - "출판사 (Publisher)"
        - "커뮤니티 (Community)"
        - "연구기관 (Research Institute)"
        - "정부기관 (Government)"
        - "비영리단체 (Non-profit)"
        - "기타 (Other)"
    validations:
      required: true

  - type: markdown
    attributes:
      value: "---"
      
  - type: markdown
    attributes:
      value: "### 🏢 조직 기본 정보"

  - type: input
    id: organization_name_ko
    attributes:
      label: 조직명 (한국어) *
      description: "조직의 정식 한국어 명칭"
      placeholder: "예: 한국인공지능연구소"
    validations:
      required: true

  - type: input
    id: organization_name_en
    attributes:
      label: 조직명 (영어) *
      description: "조직의 정식 영어 명칭"
      placeholder: "예: Korea AI Research Institute"
    validations:
      required: true

  - type: input
    id: website_url
    attributes:
      label: 공식 홈페이지 *
      description: "조직의 공식 웹사이트 URL"
      placeholder: "https://www.example.org"
    validations:
      required: true

  - type: input
    id: establishment_year
    attributes:
      label: 설립 연도
      description: "조직 설립 연도 (YYYY 형식)"
      placeholder: "예: 2010"
    validations:
      required: false

  - type: input
    id: location
    attributes:
      label: 본부 소재지
      description: "조직의 본부 또는 주요 활동 지역"
      placeholder: "예: 서울특별시, 대한민국"
    validations:
      required: false

  - type: input
    id: github_organization
    attributes:
      label: GitHub 조직 계정
      description: "해당하는 경우, GitHub Organization URL"
      placeholder: "https://github.com/organization-name"
    validations:
      required: false

  - type: markdown
    attributes:
      value: "---"
      
  - type: markdown
    attributes:
      value: "### 📋 상세 정보"

  - type: textarea
    id: business_areas
    attributes:
      label: 주요 사업 분야 *
      description: "조직의 주요 사업 분야나 활동 영역을 설명해주세요"
      placeholder: |
        예:
        - AI 연구 및 개발
        - 머신러닝 교육 프로그램 운영
        - 오픈소스 AI 도구 개발
        - AI 관련 출판 및 번역
    validations:
      required: true

  - type: checkboxes
    id: ai_ml_activities
    attributes:
      label: AI/ML 관련 활동 *
      description: "조직의 AI/ML 관련 활동을 선택하세요 (복수 선택 가능)"
      options:
        - label: "AI/ML 연구 및 개발"
          required: false
        - label: "AI 교육 및 트레이닝"
          required: false
        - label: "AI 관련 출판 및 번역"
          required: false
        - label: "오픈소스 AI 프로젝트 운영"
          required: false
        - label: "AI 컨퍼런스 및 이벤트 주최"
          required: false
        - label: "AI 표준화 활동"
          required: false
        - label: "AI 스타트업 지원 및 투자"
          required: false
        - label: "AI 윤리 및 정책 연구"
          required: false

  - type: textarea
    id: ai_projects
    attributes:
      label: 주요 AI/ML 프로젝트나 성과
      description: |
        최근 3년간 수행한 주요 AI/ML 프로젝트나 성과를 작성해주세요
      placeholder: |
        예:
        - 한국어 대화형 AI 모델 개발 (2023-2024)
        - "딥러닝 기초" 온라인 강좌 운영 (누적 수강생 10,000명)
        - 국제 AI 컨퍼런스 ICML 2023 골드 스폰서
        - AI 윤리 가이드라인 개발 및 배포
    validations:
      required: false

  - type: input
    id: team_size
    attributes:
      label: 조직 규모
      description: "전체 구성원 수 또는 AI/ML 관련 인력 수"
      placeholder: "예: 전체 50명 (AI/ML 팀 15명)"
    validations:
      required: false

  - type: markdown
    attributes:
      value: "---"
      
  - type: markdown
    attributes:
      value: "### 🌐 소셜 미디어 및 연결고리"

  - type: input
    id: linkedin_url
    attributes:
      label: LinkedIn
      description: "조직 LinkedIn 페이지 URL"
      placeholder: "https://linkedin.com/company/organization-name"
    validations:
      required: false

  - type: input
    id: twitter_url
    attributes:
      label: Twitter/X
      description: "조직 Twitter/X 계정"
      placeholder: "https://twitter.com/organization"
    validations:
      required: false

  - type: input
    id: facebook_url
    attributes:
      label: Facebook
      description: "조직 Facebook 페이지 URL"
      placeholder: "https://facebook.com/organization"
    validations:
      required: false

  - type: input
    id: youtube_url
    attributes:
      label: YouTube
      description: "조직 YouTube 채널 URL"
      placeholder: "https://youtube.com/@organization"
    validations:
      required: false

  - type: input
    id: other_links
    attributes:
      label: 기타 공식 채널
      description: "블로그, 뉴스레터, 기술 블로그 등 (쉼표로 구분)"
      placeholder: "https://blog.organization.com, https://newsletter.organization.com"
    validations:
      required: false

  - type: markdown
    attributes:
      value: "---"
      
  - type: markdown
    attributes:
      value: "### 🤝 참여 동기 및 기여 계획"

  - type: textarea
    id: participation_motivation
    attributes:
      label: 참여 동기 *
      description: |
        왜 이 용어집 프로젝트에 참여하고 싶은지 설명해주세요
      placeholder: |
        예:
        - 한국 AI 생태계 발전과 표준화에 기여하고 싶음
        - 조직의 전문성을 커뮤니티와 공유하고 싶음
        - 교육 자료로 활용하여 AI 교육 품질 향상에 기여
        - 오픈소스 정신에 공감하며 지식 공유 문화 확산
    validations:
      required: true

  - type: checkboxes
    id: contribution_types
    attributes:
      label: 기여 계획 *
      description: "어떤 방식으로 기여할 계획인가요? (복수 선택 가능)"
      options:
        - label: "용어 기여 및 검증"
          required: false
        - label: "전문 분야 자문 및 리뷰"
          required: false
        - label: "기술적 개발 지원"
          required: false
        - label: "디자인 및 UI/UX 지원"
          required: false
        - label: "번역 및 로컬라이제이션"
          required: false
        - label: "마케팅 및 홍보 지원"
          required: false
        - label: "교육 자료 활용 및 피드백"
          required: false
        - label: "재정적 후원"
          required: false
        - label: "이벤트 및 컨퍼런스 지원"
          required: false

  - type: textarea
    id: expertise_areas
    attributes:
      label: 전문 영역 *
      description: |
        조직이 검증하거나 기여할 수 있는 전문 분야를 구체적으로 작성해주세요
      placeholder: |
        예:
        - 자연어처리: 한국어 NLP 모델링, 언어 리소스 개발
        - 컴퓨터 비전: 이미지 분류, 객체 탐지 알고리즘
        - 머신러닝: 추천 시스템, 이상 탐지
        - AI 윤리: 공정성, 투명성, 책임감 있는 AI 개발
    validations:
      required: true

  - type: dropdown
    id: engagement_level
    attributes:
      label: 참여 수준
      description: "예상되는 참여 수준을 선택해주세요"
      options:
        - "적극적 참여 (정기적 기여 및 리뷰)"
        - "중간 수준 참여 (월 1-2회 기여)"
        - "가벼운 참여 (필요시 자문 및 피드백)"
        - "후원 중심 (재정적 지원 및 홍보)"
    validations:
      required: false

  - type: markdown
    attributes:
      value: "---"
      
  - type: markdown
    attributes:
      value: "### 👤 담당자 정보"

  - type: input
    id: contact_person_name
    attributes:
      label: 담당자 성명 *
      description: "조직을 대표하는 담당자의 성명"
      placeholder: "홍길동"
    validations:
      required: true

  - type: input
    id: contact_person_position
    attributes:
      label: 담당자 직책 *
      description: "담당자의 직책 또는 역할"
      placeholder: "예: 연구소장, CTO, 마케팅팀장"
    validations:
      required: true

  - type: input
    id: contact_email
    attributes:
      label: 담당자 이메일 *
      description: "연락 가능한 공식 이메일 주소"
      placeholder: "contact@organization.org"
    validations:
      required: true

  - type: input
    id: contact_phone
    attributes:
      label: 담당자 연락처
      description: "업무용 전화번호 (선택사항)"
      placeholder: "02-123-4567"
    validations:
      required: false

  - type: input
    id: github_username
    attributes:
      label: 담당자 GitHub 사용자명
      description: "GitHub에서 조직을 대표할 담당자"
      placeholder: "@username"
    validations:
      required: false

  - type: markdown
    attributes:
      value: "---"
      
  - type: markdown
    attributes:
      value: "### 🎨 브랜딩 및 로고"

  - type: textarea
    id: logo_information
    attributes:
      label: 로고 정보
      description: |
        조직 로고 사용을 위한 정보를 제공해주세요
        (이미지 링크, 다운로드 URL, 또는 첨부 파일 설명)
      placeholder: |
        - 로고 이미지 URL: https://organization.com/logo.png
        - 파일 형식: PNG, 최소 200x200px
        - 배경: 투명 또는 흰색 권장
        - 사용 조건: 출처 표기 시 자유 사용 가능
    validations:
      required: false

  - type: input
    id: brand_colors
    attributes:
      label: 브랜드 컬러
      description: "조직의 주요 브랜드 컬러 (HEX 코드)"
      placeholder: "예: #FF6B35, #1E88E5"
    validations:
      required: false

  - type: textarea
    id: branding_guidelines
    attributes:
      label: 브랜딩 사용 가이드라인
      description: |
        로고나 브랜드 요소 사용 시 주의사항이 있다면 작성해주세요
      placeholder: |
        - 로고 최소 크기: 50px
        - 로고 주변 여백: 최소 10px
        - 색상 변경 금지
        - 왜곡이나 변형 금지
    validations:
      required: false

  - type: markdown
    attributes:
      value: "---"
      
  - type: markdown
    attributes:
      value: "### 📄 검증 및 추천"

  - type: textarea
    id: verification_documents
    attributes:
      label: 조직 검증 자료
      description: |
        조직의 공식성과 실존을 증명할 수 있는 자료를 설명해주세요
        (사업자등록증, 대학인증서, 정부승인서 등)
      placeholder: |
        - 사업자등록증: 123-45-67890
        - 대학교육부 인가: 2010년 설립 승인
        - 공식 보도자료: https://news.example.com/article
        - 수상 내역: 2023년 우수 AI 연구기관 선정
    validations:
      required: false

  - type: input
    id: recommender_organizations
    attributes:
      label: 추천 조직
      description: "기존 참여 조직이나 파트너로부터의 추천이 있는 경우"
      placeholder: "예: 한국AI학회, KAIST AI연구소"
    validations:
      required: false

  - type: textarea
    id: reference_contacts
    attributes:
      label: 추천인 정보
      description: |
        조직을 추천하거나 증명할 수 있는 분의 연락처 (동의 하에)
      placeholder: |
        - 김교수 (서울대 컴퓨터공학부): kim@snu.ac.kr
        - 이박사 (ETRI 인공지능연구실): lee@etri.re.kr
    validations:
      required: false

  - type: markdown
    attributes:
      value: "---"
      
  - type: markdown
    attributes:
      value: "### ✅ 최종 확인 및 동의"

  - type: checkboxes
    id: organization_verification
    attributes:
      label: 조직 정보 확인 *
      description: "다음 항목을 확인해주세요"
      options:
        - label: "조직 정보가 모두 정확합니다"
          required: true
        - label: "공식 웹사이트가 존재하고 접근 가능합니다"
          required: true
        - label: "담당자 정보와 연락처가 정확합니다"
          required: true
        - label: "data/organizations/verified-organizations.json 파일 수정이 필요함을 이해합니다"
          required: false

  - type: checkboxes
    id: participation_agreement
    attributes:
      label: 참여 약속 *
      description: "다음 사항에 동의해주세요"
      options:
        - label: "커뮤니티 가이드라인과 행동강령을 준수하겠습니다"
          required: true
        - label: "지속적이고 건설적인 기여를 위해 노력하겠습니다"
          required: true
        - label: "조직 정보 변경 시 즉시 업데이트하겠습니다"
          required: true
        - label: "제공한 로고와 브랜드 요소 사용에 동의합니다"
          required: false

  - type: checkboxes
    id: final_agreement
    attributes:
      label: 최종 동의사항 *
      description: "다음 사항에 동의해주세요"
      options:
        - label: "이 기여는 오픈소스 라이선스 하에 제공됩니다"
          required: true
        - label: "제공한 정보가 정확하고 검증되었음을 확인합니다"
          required: true
        - label: "조직 정보가 공개적으로 표시됨을 동의합니다"
          required: true
        - label: "필요시 추가 검증 자료 제공이 가능합니다"
          required: true

  - type: textarea
    id: additional_comments
    attributes:
      label: 추가 코멘트
      description: |
        검토자에게 전달하고 싶은 추가 정보나 특별한 고려사항이 있다면 작성해주세요
      placeholder: |
        - 조직의 특별한 강점이나 차별점
        - 프로젝트에 대한 장기적 비전
        - 다른 오픈소스 프로젝트 참여 경험
        - 기타 어필하고 싶은 내용
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        
        ### 📋 참여 조직 승인 프로세스
        
        **검토 단계:**
        1. 🔍 **조직 정보 검증** (실존성, 공식성, 웹사이트 확인)
        2. 📊 **AI/ML 관련성 평가** (활동 실적, 전문성 검토)
        3. 📞 **담당자 연락 확인** (이메일 도메인, 연락처 검증)
        4. 🗣️ **커뮤니티 공개 검토** (1주일간 의견 수렴)
        5. ✅ **최종 승인 및 등록**
        
        **예상 소요 시간:** 2-3주
        
        **참여 조직 혜택:**
        - 🏆 공식 파트너 조직 인증
        - 🌟 웹사이트 파트너 섹션 노출
        - 🤝 다른 참여 조직과의 네트워킹
        - 📢 프로젝트 관련 뉴스레터 및 업데이트 수신
        - 🎯 전문 분야 관련 우선 자문 기회
        
        **주의사항:**
        - ✅ 모든 정보는 공개적으로 표시되므로 정확성을 확인해주세요
        - 🔒 조직 로고 및 브랜딩 자료는 해당 조직의 지적재산권을 존중합니다
        - 🔄 조직 정보 변경은 언제든 요청 가능합니다
        
        감사합니다! 여러분의 참여가 한국 AI/ML 생태계 발전에 큰 기여가 됩니다. 🤝