name: Validate Term Submission

on:
  pull_request:
    paths:
      - 'data/terms/*.json'
      - 'data/contributors/*.json'
      - 'data/organizations/*.json'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: npm ci

      - name: Validate term schema
        run: python scripts/validate-terms.py

      - name: Check for duplicates
        run: python scripts/check-duplicates.py

      - name: Validate sorting
        run: python scripts/validate-sorting.py

      - name: Validate search index
        run: python scripts/validate-index.py

      - name: Run tests
        run: npm run test:run

      - name: Type check
        run: npm run type-check

      - name: Lint code
        run: npm run lint

      - name: Build project
        run: npm run build